source "https://rubygems.org"
ruby "3.3.5"
gem "rails", "~> 7.1.5", ">= 7.1.5.1"
gem "sqlite3", ">= 1.4"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
end

group :development do

end

